version: '3'

services:
  sqlserver2017:
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
       - ./backup:/deal-curso-sql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DeaL@CuRsO#sQL
      - MSSQL_PID=Express
